### ISSUE TITLE
Hyperscaler Account Pool

### ISSUE THREAD

**Issue by toddnelson-sap** [kyma-incubator/compass#614] opened 2020-01-07 17:54 UTC
**Description**

Create an implementation of Hyperscaler Account pool that matches the requirements described in:
#439 

**Reasons**

Users want to easily add new Kyma clusters to Compass. Provisioner requires hyperscaler account/subscription to perform its job, but account /subscription setup is outside the scope of the Compass Provisioner. So set up the account(s) ahead of time, and create Kubernetes secrets that hold the information necessary to connect to a particular account (credentials). Label the secrets by Hyperscaler type and tenant name to track in-use and un-assigned (available for use) credentials. 

**Attachments**

**Comment by toddnelson-sap** [comment] 2020-01-07 17:58
Create a code proposal that satisfies the requirements in: #439

**Comment by janmedrek** [comment] 2020-03-09 08:19
Duplicate of: https://github.com/kyma-incubator/compass/issues/439

**Closed by janmedrek** 2020-03-09 08:19 UTC
Labels: area/management-plane
