### ISSUE TITLE
Remove dependency to Hydroform in Provisioner

### ISSUE THREAD

**Issue by akgalwas** [kyma-incubator/compass#1370] opened 2020-05-20 06:07 UTC
**Description**

Remove all dependencies to Hydroform from the Provisioner's code. 

**Reasons**

Currently implementation based on Gardener is used by default in the Provisioner. Since there is no plan to support Hydroform we need to remove it. As a result we will reduce dependencies count, binary footprint and simplify the code.

**Comment by janmedrek** [comment] 2020-06-02 08:55
duplicate of https://github.com/kyma-incubator/compass/issues/1387

**Closed by janmedrek** 2020-06-02 08:55 UTC
Labels: area/management-plane, duplicate
