### ISSUE TITLE
Make compass playground available

### ISSUE THREAD

**Issue by PK85** [kyma-incubator/compass#492] opened 2019-11-21 19:46 UTC
**Description**
Update OathKeeper configuration for Director .

**Reasons**
- Tenant mapping handler is an internal endpoint.
- GraphQL Playground is a very convenient tool for using Director, which has been available before introducing OathKeeper.

**AC**
- make compass playground available without credentials, then user needs to use credentials to execute calls
- Do not expose tenant mapping handler for OAuth flow (for other flows it is already not exported)
- Expose GraphQL Playground for Director (GET request on Gateway's /director endpoint)
   -  for OAuth 2.0, certs and JWT hosts
   -  make it unsecured
- add a simple e2e test, that endpoint is not secured

**Comment by pkosiec** [comment] 2019-11-21 19:50
This is a duplicate of https://github.com/kyma-incubator/compass/issues/416

**Comment by crabtree** [comment] 2019-11-26 08:13
@PK85 What does it mean?

> * Do not expose tenant mapping handler for OAuth flow (for other flows it is already not exported)

**Comment by crabtree** [comment] 2019-11-26 14:17
One more thing, regarding the endpoint secured with certs. In this case (mtls) we have the istio gateway configured which will not allow sending calls without client certificate present in the request. So even sending the GET request for the playground page the client certificate must be present.

**Comment by pkosiec** [comment] 2019-11-26 17:32
@crabtree yes.
See the line https://github.com/kyma-incubator/compass/blob/master/chart/compass/charts/gateway/templates/oathkeeper-rules.yaml#L11 - we're exporting all paths under gateway, so we should create more strict rules

> One more thing, regarding the endpoint secured with certs. In this case (mtls) we have the istio gateway configured which will not allow sending calls without client certificate present in the request. So even sending the GET request for the playground page the client certificate must be present.

I confirmed it with @PK85  - it is okay for us, as long as playground will be exported as well (requiring client certificate though).

So, we should create specific OathKeeper rules for the following endpoints:
- 3 x OathKeeper rule for POST `/director/graphql` - secured endpoint (for JWT, OAuth 2.0, Client certificate)
- 3 x OathKeeper rule for GET `/director` - unsecured 
- remove all `/*`rules as we should have strict ones

**Comment by crabtree** [comment] 2019-11-26 18:48
@pkosiec ok, this was exactly what I was asking for, thanks for the clarification. The only difference here will be regarding the client certificates. The client certificate needs to be present in the request for accessing the playground (it is required for mtsl handshake). In the OAuth 2 and JWT you will not need to set the token in order do reach the playground (only the actual calls to the GraphQL API will need to have the OAuth 2 or JWT tokens).

**Closed** 2019-12-20 12:40 UTC
Labels: enhancement
